### PR TITLE
Split view block

### PR DESCRIPTION
**Pull request by mind-adobe**
SplitWise block allows user to create a div split between 2 parts (left,right) with a ratio given as a param by the user

Test URLs:
- Before: https://main--aem-templ-test--mind-adobe.hlx.live/
- After: https://rewrite--aem-templ-test--mind-adobe.hlx.live/

### CODE REVIEW

**Review by hannessolo — COMMENTED** [review]
Looks good overall, some considerations:

* I saw you are using config for the 60% and turquoize. You can also add things like this to the block name in brackets in the content, so something like `Splitview (turquoize, width-60)`. The names in the brackets will be applied to the block as class names automatically
* No mobile view, but I saw you implemented mobile view for other blocks. Please remember that our best practices are mobile-first. So the "default" css is mobile view, and we use min-width queries to create the desktop styles. I saw you have some max-width queries in other blocks. Don't worry about changing it now for the other blocks, but maybe you could add a mobile-first mobile view here
* Can you run `npm run lint` locally? I saw you have some big tab indents, I thought lint would complain but maybe not :D Default is usually 2 spaces for the indent

**Comment by mind-adobe** [comment]
> * I saw you are using config for the 60% and turquoize. You can also add things like this to the block name in brackets in the content, so something like `Splitview (turquoize, width-60)`. The names in the brackets will be applied to the block as class names automatically

I am using the turqoize class in the block name in brackets, but yeah for the width I could also pass it as a class and parse it instead of using a separate cell.

> * Can you run `npm run lint` locally? I saw you have some big tab indents, I thought lint would complain but maybe not :D Default is usually 2 spaces for the indent

For me the linter complainted that I wasn't indenting with 4 spaces so I configured it that way, there is no error / warning for tabs. There are some errors for the css that I will look over, but it doesn't seem that important.

**Comment by hannessolo** [comment]
> I am using the turqoize class in the block name in brackets, but yeah for the width I could also pass it as a class and parse it instead of using a separate cell.

Ok, then you could also leave the turquoize in the brackets as the class name, and delete it from the block's body.

For reading config from the block body, you can use this function to read key-value pairs: https://github.com/mind-adobe/aem-templ-test/blob/8df227e5502c4f249175bc80443b9a0924390b0a/scripts/aem.js#L212

So in the block, you can do something like:

```
| splitview (turquoize)     |
-----------------------------
| width     |   60          |

```

Then you will get `{width: 60}` using `readBlockConfig`.

**Comment by mind-adobe** [comment]
I made the block responsive by making the layout change from horizontal to vertical on mobile and made the width transform into height% on mobile + added some media query to listen for changes.

**Pull request merged**
